# Generated by Django 4.1.2 on 2024-03-02 09:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_video_alter_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
        migrations.AlterField(
            model_name='article',
            name='poster_image',
            field=models.ImageField(upload_to='media/posters/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/videos/', validators=[core.models.Video.validate_video_file_extension]),
        ),
    ]
