# Generated by Django 4.1.2 on 2024-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_video_categories_alter_article_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
